-- =====================================================================
-- e-Dokumento: Barangay Document Request System
-- 01_schema.sql -- tables, constraints, indexes, timestamp triggers, list views
-- Run in the Supabase SQL Editor in this order:
--   01_schema.sql -> 02_functions.sql -> 03_policies.sql -> 04_storage.sql -> 05_seed.sql
-- 19 application tables in the public schema (auth.users is managed by Supabase).
-- =====================================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- 1. roles ------------------------------------------------------------
create table public.roles (
  id          smallint primary key,
  code        text not null unique
              check (code in ('admin','captain','secretary','treasurer','resident')),
  name        text not null,
  description text,
  created_at  timestamptz not null default now()
);

-- Roles are structural: RLS policies and PHP guards depend on these codes.
insert into public.roles (id, code, name, description) values
  (1, 'admin',     'Administrator',      'Configures the system, users and catalogue'),
  (2, 'captain',   'Punong Barangay',    'Approves documents that need the captain''s signature'),
  (3, 'secretary', 'Barangay Secretary', 'Verifies residents; processes, issues and releases documents'),
  (4, 'treasurer', 'Barangay Treasurer', 'Records and voids payments'),
  (5, 'resident',  'Resident',           'Requests documents and tracks their status')
on conflict (id) do nothing;

-- 2. profiles (1:1 with auth.users) ----------------------------------
create table public.profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  role_id       smallint not null default 5 references public.roles (id),
  email         text not null unique,
  full_name     text not null check (char_length(full_name) between 2 and 120),
  contact_no    text check (contact_no is null or contact_no ~ '^(09|\+639)[0-9]{9}$'),
  status        text not null default 'active' check (status in ('active','inactive')),
  last_login_at timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index profiles_role_idx on public.profiles (role_id);

-- 3. puroks -----------------------------------------------------------
create table public.puroks (
  id          smallint generated by default as identity primary key,
  name        text not null unique check (char_length(name) between 1 and 60),
  description text check (description is null or char_length(description) <= 255),
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- 4. residents --------------------------------------------------------
create table public.residents (
  id                  uuid primary key default gen_random_uuid(),
  profile_id          uuid unique references public.profiles (id) on delete set null,
  purok_id            smallint not null references public.puroks (id),
  first_name          text not null check (char_length(first_name) between 1 and 60),
  middle_name         text check (middle_name is null or char_length(middle_name) <= 60),
  last_name           text not null check (char_length(last_name) between 1 and 60),
  suffix              text check (suffix is null or char_length(suffix) <= 10),
  birth_date          date not null check (birth_date > date '1900-01-01' and birth_date <= current_date),
  sex                 text not null check (sex in ('male','female')),
  civil_status        text not null check (civil_status in ('single','married','widowed','separated','annulled')),
  street_address      text not null check (char_length(street_address) between 3 and 200),
  contact_no          text check (contact_no is null or contact_no ~ '^(09|\+639)[0-9]{9}$'),
  email               text check (email is null or email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  occupation          text check (occupation is null or char_length(occupation) <= 100),
  resident_since      date not null check (resident_since <= current_date),
  is_registered_voter boolean not null default false,
  verification_status text not null default 'unverified'
                      check (verification_status in ('unverified','pending','verified','rejected')),
  verified_by         uuid references public.profiles (id) on delete set null,
  verified_at         timestamptz,
  status              text not null default 'active'
                      check (status in ('active','moved_out','deceased','inactive')),
  created_by          uuid references public.profiles (id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  check (resident_since >= birth_date)
);
-- One person per name + birth date
create unique index residents_identity_uniq
  on public.residents (lower(last_name), lower(first_name), lower(coalesce(middle_name, '')), birth_date);
create index residents_purok_idx on public.residents (purok_id);
create index residents_verification_idx on public.residents (verification_status);
create index residents_last_name_idx on public.residents (lower(last_name));

-- 5. id_types ---------------------------------------------------------
create table public.id_types (
  id         smallint generated by default as identity primary key,
  name       text not null unique check (char_length(name) between 2 and 80),
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

-- 6. resident_verifications -------------------------------------------
create table public.resident_verifications (
  id               uuid primary key default gen_random_uuid(),
  resident_id      uuid not null references public.residents (id) on delete cascade,
  id_type_id       smallint not null references public.id_types (id),
  id_number        text not null check (char_length(id_number) between 3 and 40),
  front_image_path text not null,
  back_image_path  text,
  status           text not null default 'pending' check (status in ('pending','approved','rejected')),
  remarks          text check (remarks is null or char_length(remarks) <= 500),
  submitted_at     timestamptz not null default now(),
  reviewed_by      uuid references public.profiles (id) on delete set null,
  reviewed_at      timestamptz,
  check (status <> 'rejected' or char_length(coalesce(remarks, '')) >= 10)
);
create unique index resident_verifications_one_pending
  on public.resident_verifications (resident_id) where status = 'pending';
create index resident_verifications_status_idx on public.resident_verifications (status, submitted_at);
create index resident_verifications_resident_idx on public.resident_verifications (resident_id);

-- 7. document_types ---------------------------------------------------
create table public.document_types (
  id                        smallint generated by default as identity primary key,
  code                      text not null unique check (code ~ '^[A-Z]{2,10}$'),
  name                      text not null unique check (char_length(name) between 3 and 100),
  description               text check (description is null or char_length(description) <= 500),
  fee                       numeric(10,2) not null default 0 check (fee >= 0),
  processing_days           smallint not null default 1 check (processing_days between 0 and 30),
  validity_days             smallint check (validity_days is null or validity_days > 0),
  requires_captain_approval boolean not null default true,
  min_residency_months      smallint not null default 0 check (min_residency_months >= 0),
  once_per_lifetime         boolean not null default false,
  max_copies                smallint not null default 3 check (max_copies between 1 and 10),
  template_key              text not null default 'generic'
                            check (template_key in ('clearance','residency','indigency','business','jobseeker','generic')),
  is_active                 boolean not null default true,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

-- 8. requirements -----------------------------------------------------
create table public.requirements (
  id             smallint generated by default as identity primary key,
  name           text not null unique check (char_length(name) between 3 and 120),
  description    text check (description is null or char_length(description) <= 500),
  accepts_upload boolean not null default true,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 9. document_type_requirements (many-to-many junction) ---------------
create table public.document_type_requirements (
  document_type_id smallint not null references public.document_types (id) on delete cascade,
  requirement_id   smallint not null references public.requirements (id) on delete restrict,
  is_mandatory     boolean not null default true,
  sort_order       smallint not null default 0,
  primary key (document_type_id, requirement_id)
);
create index dtr_requirement_idx on public.document_type_requirements (requirement_id);

-- 10. purposes --------------------------------------------------------
create table public.purposes (
  id         smallint generated by default as identity primary key,
  name       text not null unique check (char_length(name) between 2 and 80),
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

-- 11. system_settings -------------------------------------------------
create table public.system_settings (
  key         text primary key check (key ~ '^[a-z_]{2,40}$'),
  value       jsonb not null,
  description text,
  updated_by  uuid references public.profiles (id) on delete set null,
  updated_at  timestamptz not null default now()
);

-- 12. document_requests -----------------------------------------------
create sequence public.request_control_seq;

create table public.document_requests (
  id               uuid primary key default gen_random_uuid(),
  control_no       text not null unique,
  resident_id      uuid not null references public.residents (id) on delete restrict,
  document_type_id smallint not null references public.document_types (id) on delete restrict,
  purpose_id       smallint not null references public.purposes (id) on delete restrict,
  purpose_details  text check (purpose_details is null or char_length(purpose_details) <= 255),
  copies           smallint not null default 1 check (copies between 1 and 10),
  extra_details    jsonb not null default '{}'::jsonb check (jsonb_typeof(extra_details) = 'object'),
  channel          text not null check (channel in ('online','walk_in')),
  fee_amount       numeric(10,2) not null default 0 check (fee_amount >= 0),
  fee_waived       boolean not null default false,
  waiver_reason    text,
  status           text not null default 'pending'
                   check (status in ('pending','under_review','for_payment','processing','for_approval',
                                     'ready_for_release','released','rejected','cancelled')),
  rejection_reason text,
  requested_by     uuid not null references public.profiles (id),
  submitted_at     timestamptz not null default now(),
  released_at      timestamptz,
  released_to      text check (released_to is null or char_length(released_to) between 2 and 120),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  check (not fee_waived or char_length(coalesce(waiver_reason, '')) between 10 and 500),
  check (status <> 'rejected' or char_length(coalesce(rejection_reason, '')) between 10 and 500),
  check (status <> 'released' or (released_at is not null and released_to is not null))
);
-- One open request per document type per resident
create unique index document_requests_one_open
  on public.document_requests (resident_id, document_type_id)
  where status not in ('released','rejected','cancelled');
create index document_requests_status_idx on public.document_requests (status, submitted_at);
create index document_requests_submitted_idx on public.document_requests (submitted_at desc);
create index document_requests_resident_idx on public.document_requests (resident_id);
create index document_requests_type_idx on public.document_requests (document_type_id);
create index document_requests_released_idx on public.document_requests (released_at);

-- 13. request_attachments ---------------------------------------------
create table public.request_attachments (
  id             uuid primary key default gen_random_uuid(),
  request_id     uuid not null references public.document_requests (id) on delete cascade,
  requirement_id smallint references public.requirements (id) on delete restrict,
  file_path      text not null unique,
  original_name  text check (original_name is null or char_length(original_name) <= 200),
  mime_type      text not null check (mime_type in ('application/pdf','image/jpeg','image/png')),
  size_bytes     integer not null check (size_bytes between 1 and 2097152),
  review_status  text not null default 'pending' check (review_status in ('pending','accepted','rejected')),
  review_remarks text check (review_remarks is null or char_length(review_remarks) <= 500),
  uploaded_by    uuid references public.profiles (id) on delete set null,
  uploaded_at    timestamptz not null default now()
);
create index request_attachments_request_idx on public.request_attachments (request_id);

-- 14. request_status_history ------------------------------------------
create table public.request_status_history (
  id          bigint generated always as identity primary key,
  request_id  uuid not null references public.document_requests (id) on delete cascade,
  from_status text,
  to_status   text not null,
  remarks     text check (remarks is null or char_length(remarks) <= 500),
  changed_by  uuid references public.profiles (id) on delete set null,
  changed_at  timestamptz not null default now()
);
create index request_status_history_request_idx on public.request_status_history (request_id, changed_at);

-- 15. payments --------------------------------------------------------
create table public.payments (
  id           uuid primary key default gen_random_uuid(),
  request_id   uuid not null references public.document_requests (id) on delete restrict,
  or_number    text not null unique check (or_number ~ '^[A-Za-z0-9-]{1,30}$'),
  amount       numeric(10,2) not null check (amount > 0),
  method       text not null check (method in ('cash','gcash','maya','bank_transfer')),
  reference_no text check (reference_no is null or char_length(reference_no) <= 60),
  status       text not null default 'posted' check (status in ('posted','voided')),
  void_reason  text,
  voided_by    uuid references public.profiles (id) on delete set null,
  voided_at    timestamptz,
  received_by  uuid not null references public.profiles (id),
  paid_at      timestamptz not null default now(),
  created_at   timestamptz not null default now(),
  check (method = 'cash' or reference_no is not null),
  check (status <> 'voided' or (char_length(coalesce(void_reason, '')) between 10 and 500 and voided_at is not null))
);
create unique index payments_one_posted on public.payments (request_id) where status = 'posted';
create index payments_paid_at_idx on public.payments (paid_at);
create index payments_request_idx on public.payments (request_id);

-- 16. barangay_officials ----------------------------------------------
create table public.barangay_officials (
  id             smallint generated by default as identity primary key,
  full_name      text not null check (char_length(full_name) between 3 and 120),
  position       text not null
                 check (position in ('punong_barangay','kagawad','secretary','treasurer','sk_chairperson')),
  committee      text check (committee is null or char_length(committee) <= 120),
  term_start     date not null,
  term_end       date not null,
  signature_path text,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  check (term_end > term_start)
);
create unique index barangay_officials_one_captain
  on public.barangay_officials (position) where position = 'punong_barangay' and is_active;

-- 17. issued_documents (1:1 with document_requests) -------------------
create sequence public.issued_document_seq;

create table public.issued_documents (
  id                uuid primary key default gen_random_uuid(),
  request_id        uuid not null unique references public.document_requests (id) on delete restrict,
  document_no       text not null unique,
  verification_code text not null unique check (verification_code ~ '^[0-9A-F]{10}$'),
  signatory_id      smallint not null references public.barangay_officials (id),
  prepared_by       uuid references public.profiles (id) on delete set null,
  issued_at         timestamptz not null default now(),
  valid_until       date,
  print_count       integer not null default 0 check (print_count >= 0),
  status            text not null default 'valid' check (status in ('valid','revoked')),
  revoked_reason    text,
  revoked_at        timestamptz,
  created_at        timestamptz not null default now(),
  check (status <> 'revoked' or (char_length(coalesce(revoked_reason, '')) between 10 and 500 and revoked_at is not null))
);
create index issued_documents_issued_at_idx on public.issued_documents (issued_at desc);
create index issued_documents_signatory_idx on public.issued_documents (signatory_id);

-- 18. notifications ---------------------------------------------------
create table public.notifications (
  id           bigint generated always as identity primary key,
  recipient_id uuid not null references public.profiles (id) on delete cascade,
  request_id   uuid references public.document_requests (id) on delete set null,
  title        text not null check (char_length(title) between 1 and 120),
  message      text not null,
  is_read      boolean not null default false,
  created_at   timestamptz not null default now()
);
create index notifications_recipient_idx on public.notifications (recipient_id, is_read, created_at desc);

-- 19. audit_logs (append-only) ----------------------------------------
create table public.audit_logs (
  id          bigint generated always as identity primary key,
  actor_id    uuid references public.profiles (id) on delete set null,
  action      text not null check (char_length(action) between 2 and 40),
  entity_type text not null check (char_length(entity_type) between 2 and 60),
  entity_id   text,
  details     jsonb not null default '{}'::jsonb,
  ip_address  inet,
  user_agent  text,
  created_at  timestamptz not null default now()
);
create index audit_logs_created_idx on public.audit_logs (created_at desc);
create index audit_logs_actor_idx on public.audit_logs (actor_id, created_at desc);
create index audit_logs_entity_idx on public.audit_logs (entity_type, entity_id);

-- updated_at triggers ---------------------------------------------------
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger puroks_updated_at before update on public.puroks for each row execute function public.set_updated_at();
create trigger residents_updated_at before update on public.residents for each row execute function public.set_updated_at();
create trigger document_types_updated_at before update on public.document_types for each row execute function public.set_updated_at();
create trigger requirements_updated_at before update on public.requirements for each row execute function public.set_updated_at();
create trigger system_settings_updated_at before update on public.system_settings for each row execute function public.set_updated_at();
create trigger document_requests_updated_at before update on public.document_requests for each row execute function public.set_updated_at();
create trigger barangay_officials_updated_at before update on public.barangay_officials for each row execute function public.set_updated_at();

-- Control number <PREFIX>-<YEAR>-<000001> -------------------------------
create or replace function public.set_request_control_no()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_prefix text;
begin
  if new.control_no is null or new.control_no = '' then
    select s.value #>> '{}' into v_prefix from public.system_settings s where s.key = 'control_prefix';
    v_prefix := upper(coalesce(nullif(v_prefix, ''), 'REQ'));
    new.control_no := v_prefix || '-' || to_char(now() at time zone 'Asia/Manila', 'YYYY') || '-'
                      || lpad(nextval('public.request_control_seq')::text, 6, '0');
  end if;
  return new;
end;
$$;

create trigger document_requests_control_no
  before insert on public.document_requests
  for each row execute function public.set_request_control_no();

-- Listing views (not tables). security_invoker = on makes them obey the caller's RLS.
create or replace view public.request_list with (security_invoker = on) as
select
  d.id, d.control_no, d.status, d.channel, d.copies, d.fee_amount, d.fee_waived,
  d.submitted_at, d.released_at, d.updated_at,
  d.resident_id, r.first_name, r.last_name,
  concat_ws(' ', r.first_name, r.middle_name, r.last_name, r.suffix) as resident_name,
  r.purok_id, pk.name as purok_name,
  d.document_type_id, t.name as document_type, t.code as document_code, t.processing_days,
  d.purpose_id, pu.name as purpose,
  (d.status in ('pending','under_review','processing','for_approval')
     and d.submitted_at + make_interval(days => t.processing_days::integer) < now()) as is_overdue,
  lower(d.control_no || ' ' || concat_ws(' ', r.first_name, r.middle_name, r.last_name)) as search_text
from public.document_requests d
join public.residents r on r.id = d.resident_id
join public.document_types t on t.id = d.document_type_id
join public.purposes pu on pu.id = d.purpose_id
join public.puroks pk on pk.id = r.purok_id;

create or replace view public.payment_list with (security_invoker = on) as
select
  p.id, p.or_number, p.amount, p.method, p.reference_no, p.status, p.paid_at,
  p.void_reason, p.voided_at, p.received_by, pr.full_name as received_by_name,
  p.request_id, d.control_no, d.status as request_status, t.name as document_type,
  concat_ws(' ', r.first_name, r.last_name) as resident_name,
  lower(p.or_number || ' ' || d.control_no || ' ' || r.first_name || ' ' || r.last_name) as search_text
from public.payments p
join public.document_requests d on d.id = p.request_id
join public.residents r on r.id = d.resident_id
join public.document_types t on t.id = d.document_type_id
left join public.profiles pr on pr.id = p.received_by;

create or replace view public.issued_document_list with (security_invoker = on) as
select
  i.id, i.document_no, i.verification_code, i.issued_at, i.valid_until, i.status, i.print_count,
  i.revoked_reason, i.request_id, d.control_no, d.status as request_status,
  d.document_type_id, t.name as document_type,
  concat_ws(' ', r.first_name, r.last_name) as resident_name,
  lower(i.document_no || ' ' || d.control_no || ' ' || r.first_name || ' ' || r.last_name) as search_text
from public.issued_documents i
join public.document_requests d on d.id = i.request_id
join public.residents r on r.id = d.resident_id
join public.document_types t on t.id = d.document_type_id;
